# SPDX-FileCopyrightText: 2021 Fraunhofer Institute for Experimental Software Engineering IESE
#
# SPDX-License-Identifier: CC0-1.0

accepted = [
    "Apache-2.0",
    "BSD-3-Clause",
    "EPL-2.0",
    "MIT",
    "MPL-2.0"
]
