# This Action is triggered when a PR with the label 'release' is closed and merged into 'main'.
# It publishes the crates in the repo to crates.io.

on:
  pull_request:
    branches: [main]
    types: [closed]

name: Release on crates.io

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release')

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Rust toolchains
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - name: Publish to crates.io
        run: |
          cargo install cargo-workspaces
          cargo workspaces publish --from-git --token ${{ secrets.CRATES_IO_TOKEN }} custom `echo "${{ github.head_ref }}" | cut -c2-`
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          custom_tag: ${{ steps.extract_branch.outputs.branch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}