# SPDX-FileCopyrightText: 2021 Andreas Schmidt <andreas.schmidt@iese.fraunhofer.de>
#
# SPDX-License-Identifier: EPL-2.0

# This Action is triggered when a version is tagged.
# It publishes the crates in the repo to crates.io.

on:
  push:
    tags:
      - '*'
  pull_request:

name: Release on crates.io

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Rust toolchains
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - name: Publish to crates.io
        run: |
          cargo install cargo-workspaces
          cargo workspaces publish --from-git --token ${{ secrets.CRATES_IO_TOKEN }} custom `echo "${{ SOURCE_TAG }}" | cut -c2-`
        env:
          SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
          SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}

      - name: Create a GitHub release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.branch_name.outputs.SOURCE_TAG }}
          release_name: Release ${{ steps.branch_name.outputs.SOURCE_TAG }}
          body: ${{ steps.branch_name.outputs.SOURCE_TAG }}